version: '3'

services:
  bot:
    container_name: wealthy-bot
    build: .
    env_file: .env
    volumes:
      - ./persisted/bot:/app/persisted/bot
    restart: unless-stopped
    networks:
      - default
      - ubuntu_caddy
    depends_on:
      - db
  db:
    image: postgres:15
    env_file: .env.db
    environment:
      POSTGRES_USER: wealthy-bot
    volumes:
      - ./persisted/db/data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  ubuntu_caddy:
    external: true