services:
  app:
    container_name: wealthy-app
    build: ./wealthy-app
    environment:
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      GUILD_ID: "${GUILD_ID}"
      DATABASE_URL: "postgresql://wealthy:${POSTGRES_PASSWORD}@db/wealthy"
      ROLES: "${ROLES}"
    restart: unless-stopped
    networks:
      - default
      - caddy_default
    depends_on:
      - db
  bot:
    container_name: wealthy-bot
    build: ./wealthy-bot
    environment:
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      DATABASE_URL: "postgresql://wealthy:${POSTGRES_PASSWORD}@db/wealthy"
      WEBHOOK_URL: "${WEBHOOK_URL}"
      OPENAI_KEY: "${OPENAI_KEY}"
    restart: unless-stopped
    networks:
      - default
      - caddy_default
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: "wealthy"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - wealthy-data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  caddy_default:
    external: true

volumes:
  wealthy-data:
